### ISSUE TITLE
Button tap ignored on iPadOS

### ISSUE THREAD

**Issue by gbmksquare** [cleanios/LetSwift#85]
View Homepage and View Ticket buttons on home tab are not responding to tap on iPadOS

**Comment by yoee** [comment]
@gbmksquare 시뮬(pro 13.1)에서는 정상작동 하는데, 실 기기에서 안되는 건가요?

**Comment by gbmksquare** [comment]
클립된 이미지가 실제로는 tap area를 먹고 있어 발생한 것으로 발견
